[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wpi_verl_plugin"
version = "0.1.0"
description = "WPI checkpoint engine plugin for verl"
authors = [
    { name = "Google LLC" }
]
dependencies = [
    "torch",
    "ray",
    "pyzmq",
    "grpcio>=1.60.0",
    "protobuf"
]

[tool.setuptools]
packages = ["wpi_verl_plugin", "wpi_verl_plugin.proto"]

[tool.setuptools.package-dir]
wpi_verl_plugin = "."
