resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: us-west1-docker.pkg.dev/gke-shared-ai-dev/rl-weight-transfer/wpi-operator
  newTag: latest
