apiVersion: wpi.io/v1alpha1
kind: WeightClaim
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: weightclaim-sample
spec:
  weightBufferName: "weightbuffer-sample"
