// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: wpi.proto

package wpi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPluginCapabilitiesResponse_PluginCapability_Capability int32

const (
	GetPluginCapabilitiesResponse_PluginCapability_UNKNOWN               GetPluginCapabilitiesResponse_PluginCapability_Capability = 0
	GetPluginCapabilitiesResponse_PluginCapability_CROSS_VENDOR_TRANSFER GetPluginCapabilitiesResponse_PluginCapability_Capability = 1
	GetPluginCapabilitiesResponse_PluginCapability_ON_THE_FLY_RESHAPING  GetPluginCapabilitiesResponse_PluginCapability_Capability = 2
	GetPluginCapabilitiesResponse_PluginCapability_PRE_STAGING_SUPPORT   GetPluginCapabilitiesResponse_PluginCapability_Capability = 3
)

// Enum value maps for GetPluginCapabilitiesResponse_PluginCapability_Capability.
var (
	GetPluginCapabilitiesResponse_PluginCapability_Capability_name = map[int32]string{
		0: "UNKNOWN",
		1: "CROSS_VENDOR_TRANSFER",
		2: "ON_THE_FLY_RESHAPING",
		3: "PRE_STAGING_SUPPORT",
	}
	GetPluginCapabilitiesResponse_PluginCapability_Capability_value = map[string]int32{
		"UNKNOWN":               0,
		"CROSS_VENDOR_TRANSFER": 1,
		"ON_THE_FLY_RESHAPING":  2,
		"PRE_STAGING_SUPPORT":   3,
	}
)

func (x GetPluginCapabilitiesResponse_PluginCapability_Capability) Enum() *GetPluginCapabilitiesResponse_PluginCapability_Capability {
	p := new(GetPluginCapabilitiesResponse_PluginCapability_Capability)
	*p = x
	return p
}

func (x GetPluginCapabilitiesResponse_PluginCapability_Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPluginCapabilitiesResponse_PluginCapability_Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_wpi_proto_enumTypes[0].Descriptor()
}

func (GetPluginCapabilitiesResponse_PluginCapability_Capability) Type() protoreflect.EnumType {
	return &file_wpi_proto_enumTypes[0]
}

func (x GetPluginCapabilitiesResponse_PluginCapability_Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPluginCapabilitiesResponse_PluginCapability_Capability.Descriptor instead.
func (GetPluginCapabilitiesResponse_PluginCapability_Capability) EnumDescriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{3, 0, 0}
}

type LayoutDescriptor_LayoutType int32

const (
	LayoutDescriptor_ROW_MAJOR              LayoutDescriptor_LayoutType = 0
	LayoutDescriptor_COLUMN_MAJOR           LayoutDescriptor_LayoutType = 1
	LayoutDescriptor_VENDOR_SPECIFIC_TILING LayoutDescriptor_LayoutType = 2
)

// Enum value maps for LayoutDescriptor_LayoutType.
var (
	LayoutDescriptor_LayoutType_name = map[int32]string{
		0: "ROW_MAJOR",
		1: "COLUMN_MAJOR",
		2: "VENDOR_SPECIFIC_TILING",
	}
	LayoutDescriptor_LayoutType_value = map[string]int32{
		"ROW_MAJOR":              0,
		"COLUMN_MAJOR":           1,
		"VENDOR_SPECIFIC_TILING": 2,
	}
)

func (x LayoutDescriptor_LayoutType) Enum() *LayoutDescriptor_LayoutType {
	p := new(LayoutDescriptor_LayoutType)
	*p = x
	return p
}

func (x LayoutDescriptor_LayoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayoutDescriptor_LayoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_wpi_proto_enumTypes[1].Descriptor()
}

func (LayoutDescriptor_LayoutType) Type() protoreflect.EnumType {
	return &file_wpi_proto_enumTypes[1]
}

func (x LayoutDescriptor_LayoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayoutDescriptor_LayoutType.Descriptor instead.
func (LayoutDescriptor_LayoutType) EnumDescriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{16, 0}
}

type GetPluginInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginInfoRequest) Reset() {
	*x = GetPluginInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoRequest) ProtoMessage() {}

func (x *GetPluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{0}
}

type GetPluginInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VendorVersion string `protobuf:"bytes,2,opt,name=vendor_version,json=vendorVersion,proto3" json:"vendor_version,omitempty"`
}

func (x *GetPluginInfoResponse) Reset() {
	*x = GetPluginInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoResponse) ProtoMessage() {}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{1}
}

func (x *GetPluginInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPluginInfoResponse) GetVendorVersion() string {
	if x != nil {
		return x.VendorVersion
	}
	return ""
}

type GetPluginCapabilitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginCapabilitiesRequest) Reset() {
	*x = GetPluginCapabilitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginCapabilitiesRequest) ProtoMessage() {}

func (x *GetPluginCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetPluginCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{2}
}

type GetPluginCapabilitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capabilities []*GetPluginCapabilitiesResponse_PluginCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *GetPluginCapabilitiesResponse) Reset() {
	*x = GetPluginCapabilitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginCapabilitiesResponse) ProtoMessage() {}

func (x *GetPluginCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetPluginCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{3}
}

func (x *GetPluginCapabilitiesResponse) GetCapabilities() []*GetPluginCapabilitiesResponse_PluginCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CreateWeightBufferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BufferId  string `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	SizeBytes uint64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
}

func (x *CreateWeightBufferRequest) Reset() {
	*x = CreateWeightBufferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeightBufferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeightBufferRequest) ProtoMessage() {}

func (x *CreateWeightBufferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeightBufferRequest.ProtoReflect.Descriptor instead.
func (*CreateWeightBufferRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWeightBufferRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *CreateWeightBufferRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type CreateWeightBufferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWeightBufferResponse) Reset() {
	*x = CreateWeightBufferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWeightBufferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWeightBufferResponse) ProtoMessage() {}

func (x *CreateWeightBufferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWeightBufferResponse.ProtoReflect.Descriptor instead.
func (*CreateWeightBufferResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{5}
}

type AuthorizeTransferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BufferId     string `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	TargetNodeId string `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
}

func (x *AuthorizeTransferRequest) Reset() {
	*x = AuthorizeTransferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeTransferRequest) ProtoMessage() {}

func (x *AuthorizeTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeTransferRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeTransferRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{6}
}

func (x *AuthorizeTransferRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *AuthorizeTransferRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type AuthorizeTransferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rkey []byte `protobuf:"bytes,1,opt,name=rkey,proto3" json:"rkey,omitempty"`
}

func (x *AuthorizeTransferResponse) Reset() {
	*x = AuthorizeTransferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeTransferResponse) ProtoMessage() {}

func (x *AuthorizeTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeTransferResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeTransferResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizeTransferResponse) GetRkey() []byte {
	if x != nil {
		return x.Rkey
	}
	return nil
}

type QueryTopologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *QueryTopologyRequest) Reset() {
	*x = QueryTopologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTopologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopologyRequest) ProtoMessage() {}

func (x *QueryTopologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopologyRequest.ProtoReflect.Descriptor instead.
func (*QueryTopologyRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTopologyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type QueryTopologyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopologyInfo string `protobuf:"bytes,1,opt,name=topology_info,json=topologyInfo,proto3" json:"topology_info,omitempty"`
}

func (x *QueryTopologyResponse) Reset() {
	*x = QueryTopologyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopologyResponse) ProtoMessage() {}

func (x *QueryTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopologyResponse.ProtoReflect.Descriptor instead.
func (*QueryTopologyResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{9}
}

func (x *QueryTopologyResponse) GetTopologyInfo() string {
	if x != nil {
		return x.TopologyInfo
	}
	return ""
}

type NodeRegisterWeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BufferId  string `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	SizeBytes uint64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
}

func (x *NodeRegisterWeightRequest) Reset() {
	*x = NodeRegisterWeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRegisterWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterWeightRequest) ProtoMessage() {}

func (x *NodeRegisterWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterWeightRequest.ProtoReflect.Descriptor instead.
func (*NodeRegisterWeightRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{10}
}

func (x *NodeRegisterWeightRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *NodeRegisterWeightRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type NodeRegisterWeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DmaBufHandle string `protobuf:"bytes,1,opt,name=dma_buf_handle,json=dmaBufHandle,proto3" json:"dma_buf_handle,omitempty"`
}

func (x *NodeRegisterWeightResponse) Reset() {
	*x = NodeRegisterWeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRegisterWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterWeightResponse) ProtoMessage() {}

func (x *NodeRegisterWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterWeightResponse.ProtoReflect.Descriptor instead.
func (*NodeRegisterWeightResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{11}
}

func (x *NodeRegisterWeightResponse) GetDmaBufHandle() string {
	if x != nil {
		return x.DmaBufHandle
	}
	return ""
}

type NodeStageWeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimId    string `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	BufferId   string `protobuf:"bytes,2,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	SourcePath string `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	SizeBytes  uint64 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
}

func (x *NodeStageWeightRequest) Reset() {
	*x = NodeStageWeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStageWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStageWeightRequest) ProtoMessage() {}

func (x *NodeStageWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStageWeightRequest.ProtoReflect.Descriptor instead.
func (*NodeStageWeightRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{12}
}

func (x *NodeStageWeightRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *NodeStageWeightRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *NodeStageWeightRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *NodeStageWeightRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type NodeStageWeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodeStageWeightResponse) Reset() {
	*x = NodeStageWeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeStageWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStageWeightResponse) ProtoMessage() {}

func (x *NodeStageWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStageWeightResponse.ProtoReflect.Descriptor instead.
func (*NodeStageWeightResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{13}
}

type NodeUnstageWeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimId string `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
}

func (x *NodeUnstageWeightRequest) Reset() {
	*x = NodeUnstageWeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeUnstageWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUnstageWeightRequest) ProtoMessage() {}

func (x *NodeUnstageWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUnstageWeightRequest.ProtoReflect.Descriptor instead.
func (*NodeUnstageWeightRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{14}
}

func (x *NodeUnstageWeightRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type NodeUnstageWeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodeUnstageWeightResponse) Reset() {
	*x = NodeUnstageWeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeUnstageWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUnstageWeightResponse) ProtoMessage() {}

func (x *NodeUnstageWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUnstageWeightResponse.ProtoReflect.Descriptor instead.
func (*NodeUnstageWeightResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{15}
}

type LayoutDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type           LayoutDescriptor_LayoutType `protobuf:"varint,1,opt,name=type,proto3,enum=wpi.v1alpha1.LayoutDescriptor_LayoutType" json:"type,omitempty"`
	TilingMetadata []byte                      `protobuf:"bytes,2,opt,name=tiling_metadata,json=tilingMetadata,proto3" json:"tiling_metadata,omitempty"` // Opaque blob for vendor-specific tiling logic
}

func (x *LayoutDescriptor) Reset() {
	*x = LayoutDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutDescriptor) ProtoMessage() {}

func (x *LayoutDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutDescriptor.ProtoReflect.Descriptor instead.
func (*LayoutDescriptor) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{16}
}

func (x *LayoutDescriptor) GetType() LayoutDescriptor_LayoutType {
	if x != nil {
		return x.Type
	}
	return LayoutDescriptor_ROW_MAJOR
}

func (x *LayoutDescriptor) GetTilingMetadata() []byte {
	if x != nil {
		return x.TilingMetadata
	}
	return nil
}

type NodePropagateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BufferId      string            `protobuf:"bytes,1,opt,name=buffer_id,json=bufferId,proto3" json:"buffer_id,omitempty"`
	TargetNodeIds []string          `protobuf:"bytes,2,rep,name=target_node_ids,json=targetNodeIds,proto3" json:"target_node_ids,omitempty"`
	TargetLayout  *LayoutDescriptor `protobuf:"bytes,3,opt,name=target_layout,json=targetLayout,proto3" json:"target_layout,omitempty"`
}

func (x *NodePropagateRequest) Reset() {
	*x = NodePropagateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodePropagateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePropagateRequest) ProtoMessage() {}

func (x *NodePropagateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePropagateRequest.ProtoReflect.Descriptor instead.
func (*NodePropagateRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{17}
}

func (x *NodePropagateRequest) GetBufferId() string {
	if x != nil {
		return x.BufferId
	}
	return ""
}

func (x *NodePropagateRequest) GetTargetNodeIds() []string {
	if x != nil {
		return x.TargetNodeIds
	}
	return nil
}

func (x *NodePropagateRequest) GetTargetLayout() *LayoutDescriptor {
	if x != nil {
		return x.TargetLayout
	}
	return nil
}

type NodePropagateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NodePropagateResponse) Reset() {
	*x = NodePropagateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodePropagateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePropagateResponse) ProtoMessage() {}

func (x *NodePropagateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePropagateResponse.ProtoReflect.Descriptor instead.
func (*NodePropagateResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{18}
}

type NodeTranslateAndMapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClaimId      string            `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	SourceLayout *LayoutDescriptor `protobuf:"bytes,2,opt,name=source_layout,json=sourceLayout,proto3" json:"source_layout,omitempty"`
	TargetLayout *LayoutDescriptor `protobuf:"bytes,3,opt,name=target_layout,json=targetLayout,proto3" json:"target_layout,omitempty"`
}

func (x *NodeTranslateAndMapRequest) Reset() {
	*x = NodeTranslateAndMapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeTranslateAndMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTranslateAndMapRequest) ProtoMessage() {}

func (x *NodeTranslateAndMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTranslateAndMapRequest.ProtoReflect.Descriptor instead.
func (*NodeTranslateAndMapRequest) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{19}
}

func (x *NodeTranslateAndMapRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *NodeTranslateAndMapRequest) GetSourceLayout() *LayoutDescriptor {
	if x != nil {
		return x.SourceLayout
	}
	return nil
}

func (x *NodeTranslateAndMapRequest) GetTargetLayout() *LayoutDescriptor {
	if x != nil {
		return x.TargetLayout
	}
	return nil
}

type NodeTranslateAndMapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DevicePath string `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"` // e.g., /dev/wpi/weights/layer82
}

func (x *NodeTranslateAndMapResponse) Reset() {
	*x = NodeTranslateAndMapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeTranslateAndMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeTranslateAndMapResponse) ProtoMessage() {}

func (x *NodeTranslateAndMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeTranslateAndMapResponse.ProtoReflect.Descriptor instead.
func (*NodeTranslateAndMapResponse) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{20}
}

func (x *NodeTranslateAndMapResponse) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

type GetPluginCapabilitiesResponse_PluginCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capability GetPluginCapabilitiesResponse_PluginCapability_Capability `protobuf:"varint,1,opt,name=capability,proto3,enum=wpi.v1alpha1.GetPluginCapabilitiesResponse_PluginCapability_Capability" json:"capability,omitempty"`
}

func (x *GetPluginCapabilitiesResponse_PluginCapability) Reset() {
	*x = GetPluginCapabilitiesResponse_PluginCapability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wpi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginCapabilitiesResponse_PluginCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginCapabilitiesResponse_PluginCapability) ProtoMessage() {}

func (x *GetPluginCapabilitiesResponse_PluginCapability) ProtoReflect() protoreflect.Message {
	mi := &file_wpi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginCapabilitiesResponse_PluginCapability.ProtoReflect.Descriptor instead.
func (*GetPluginCapabilitiesResponse_PluginCapability) Descriptor() ([]byte, []int) {
	return file_wpi_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetPluginCapabilitiesResponse_PluginCapability) GetCapability() GetPluginCapabilitiesResponse_PluginCapability_Capability {
	if x != nil {
		return x.Capability
	}
	return GetPluginCapabilitiesResponse_PluginCapability_UNKNOWN
}

var File_wpi_proto protoreflect.FileDescriptor

var file_wpi_proto_rawDesc = []byte{
	0x0a, 0x09, 0x77, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x52, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe8, 0x02, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x63, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0xe4, 0x01, 0x0a, 0x10, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x67,
	0x0a, 0x0a, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x47, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x67, 0x0a, 0x0a, 0x43, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x52, 0x4f, 0x53, 0x53, 0x5f, 0x56, 0x45, 0x4e, 0x44,
	0x4f, 0x52, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x46, 0x45, 0x52, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x4f, 0x4e, 0x5f, 0x54, 0x48, 0x45, 0x5f, 0x46, 0x4c, 0x59, 0x5f, 0x52, 0x45, 0x53, 0x48,
	0x41, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x52, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x03,
	0x22, 0x57, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69,
	0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x18, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x19, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x72, 0x6b, 0x65, 0x79, 0x22, 0x2f, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x57, 0x0a, 0x19, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22,
	0x42, 0x0a, 0x1a, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x64, 0x6d, 0x61, 0x5f, 0x62, 0x75, 0x66, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6d, 0x61, 0x42, 0x75, 0x66, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x16, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x69, 0x7a,
	0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x35, 0x0a, 0x18, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x4e, 0x6f, 0x64, 0x65,
	0x55, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc5, 0x01, 0x0a, 0x10, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6c,
	0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x74, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x49, 0x0a, 0x0a, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0d, 0x0a, 0x09, 0x52, 0x4f, 0x57, 0x5f, 0x4d, 0x41, 0x4a, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4d, 0x41, 0x4a, 0x4f, 0x52, 0x10,
	0x01, 0x12, 0x1a, 0x0a, 0x16, 0x56, 0x45, 0x4e, 0x44, 0x4f, 0x52, 0x5f, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x43, 0x5f, 0x54, 0x49, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x22, 0xa0, 0x01,
	0x0a, 0x14, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x73, 0x12, 0x43, 0x0a, 0x0d, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x1a, 0x4e, 0x6f,
	0x64, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x61,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x77, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x43, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52,
	0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x22, 0x3e, 0x0a,
	0x1b, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x64, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x32, 0xdd, 0x01,
	0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x58, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x22, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x70, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x12, 0x2a, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbc, 0x02,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x77, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x12, 0x26, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x77, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x6f, 0x70, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x12, 0x22, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x82, 0x04, 0x0a,
	0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x67, 0x0a, 0x12,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x27, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x77, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x67, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x6e, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x26, 0x2e, 0x77, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x6e,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x55, 0x6e, 0x73, 0x74, 0x61, 0x67, 0x65, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x77,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x61, 0x70, 0x12, 0x28, 0x2e, 0x77,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x61, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x77, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x64, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x25, 0x5a, 0x23, 0x77, 0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x38, 0x73,
	0x2e, 0x69, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x77, 0x70, 0x69, 0x3b, 0x77, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wpi_proto_rawDescOnce sync.Once
	file_wpi_proto_rawDescData = file_wpi_proto_rawDesc
)

func file_wpi_proto_rawDescGZIP() []byte {
	file_wpi_proto_rawDescOnce.Do(func() {
		file_wpi_proto_rawDescData = protoimpl.X.CompressGZIP(file_wpi_proto_rawDescData)
	})
	return file_wpi_proto_rawDescData
}

var file_wpi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wpi_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_wpi_proto_goTypes = []interface{}{
	(GetPluginCapabilitiesResponse_PluginCapability_Capability)(0), // 0: wpi.v1alpha1.GetPluginCapabilitiesResponse.PluginCapability.Capability
	(LayoutDescriptor_LayoutType)(0),                               // 1: wpi.v1alpha1.LayoutDescriptor.LayoutType
	(*GetPluginInfoRequest)(nil),                                   // 2: wpi.v1alpha1.GetPluginInfoRequest
	(*GetPluginInfoResponse)(nil),                                  // 3: wpi.v1alpha1.GetPluginInfoResponse
	(*GetPluginCapabilitiesRequest)(nil),                           // 4: wpi.v1alpha1.GetPluginCapabilitiesRequest
	(*GetPluginCapabilitiesResponse)(nil),                          // 5: wpi.v1alpha1.GetPluginCapabilitiesResponse
	(*CreateWeightBufferRequest)(nil),                              // 6: wpi.v1alpha1.CreateWeightBufferRequest
	(*CreateWeightBufferResponse)(nil),                             // 7: wpi.v1alpha1.CreateWeightBufferResponse
	(*AuthorizeTransferRequest)(nil),                               // 8: wpi.v1alpha1.AuthorizeTransferRequest
	(*AuthorizeTransferResponse)(nil),                              // 9: wpi.v1alpha1.AuthorizeTransferResponse
	(*QueryTopologyRequest)(nil),                                   // 10: wpi.v1alpha1.QueryTopologyRequest
	(*QueryTopologyResponse)(nil),                                  // 11: wpi.v1alpha1.QueryTopologyResponse
	(*NodeRegisterWeightRequest)(nil),                              // 12: wpi.v1alpha1.NodeRegisterWeightRequest
	(*NodeRegisterWeightResponse)(nil),                             // 13: wpi.v1alpha1.NodeRegisterWeightResponse
	(*NodeStageWeightRequest)(nil),                                 // 14: wpi.v1alpha1.NodeStageWeightRequest
	(*NodeStageWeightResponse)(nil),                                // 15: wpi.v1alpha1.NodeStageWeightResponse
	(*NodeUnstageWeightRequest)(nil),                               // 16: wpi.v1alpha1.NodeUnstageWeightRequest
	(*NodeUnstageWeightResponse)(nil),                              // 17: wpi.v1alpha1.NodeUnstageWeightResponse
	(*LayoutDescriptor)(nil),                                       // 18: wpi.v1alpha1.LayoutDescriptor
	(*NodePropagateRequest)(nil),                                   // 19: wpi.v1alpha1.NodePropagateRequest
	(*NodePropagateResponse)(nil),                                  // 20: wpi.v1alpha1.NodePropagateResponse
	(*NodeTranslateAndMapRequest)(nil),                             // 21: wpi.v1alpha1.NodeTranslateAndMapRequest
	(*NodeTranslateAndMapResponse)(nil),                            // 22: wpi.v1alpha1.NodeTranslateAndMapResponse
	(*GetPluginCapabilitiesResponse_PluginCapability)(nil),         // 23: wpi.v1alpha1.GetPluginCapabilitiesResponse.PluginCapability
}
var file_wpi_proto_depIdxs = []int32{
	23, // 0: wpi.v1alpha1.GetPluginCapabilitiesResponse.capabilities:type_name -> wpi.v1alpha1.GetPluginCapabilitiesResponse.PluginCapability
	1,  // 1: wpi.v1alpha1.LayoutDescriptor.type:type_name -> wpi.v1alpha1.LayoutDescriptor.LayoutType
	18, // 2: wpi.v1alpha1.NodePropagateRequest.target_layout:type_name -> wpi.v1alpha1.LayoutDescriptor
	18, // 3: wpi.v1alpha1.NodeTranslateAndMapRequest.source_layout:type_name -> wpi.v1alpha1.LayoutDescriptor
	18, // 4: wpi.v1alpha1.NodeTranslateAndMapRequest.target_layout:type_name -> wpi.v1alpha1.LayoutDescriptor
	0,  // 5: wpi.v1alpha1.GetPluginCapabilitiesResponse.PluginCapability.capability:type_name -> wpi.v1alpha1.GetPluginCapabilitiesResponse.PluginCapability.Capability
	2,  // 6: wpi.v1alpha1.IdentityService.GetPluginInfo:input_type -> wpi.v1alpha1.GetPluginInfoRequest
	4,  // 7: wpi.v1alpha1.IdentityService.GetPluginCapabilities:input_type -> wpi.v1alpha1.GetPluginCapabilitiesRequest
	6,  // 8: wpi.v1alpha1.ControllerService.CreateWeightBuffer:input_type -> wpi.v1alpha1.CreateWeightBufferRequest
	8,  // 9: wpi.v1alpha1.ControllerService.AuthorizeTransfer:input_type -> wpi.v1alpha1.AuthorizeTransferRequest
	10, // 10: wpi.v1alpha1.ControllerService.QueryTopology:input_type -> wpi.v1alpha1.QueryTopologyRequest
	12, // 11: wpi.v1alpha1.NodeService.NodeRegisterWeight:input_type -> wpi.v1alpha1.NodeRegisterWeightRequest
	14, // 12: wpi.v1alpha1.NodeService.NodeStageWeight:input_type -> wpi.v1alpha1.NodeStageWeightRequest
	16, // 13: wpi.v1alpha1.NodeService.NodeUnstageWeight:input_type -> wpi.v1alpha1.NodeUnstageWeightRequest
	19, // 14: wpi.v1alpha1.NodeService.NodePropagate:input_type -> wpi.v1alpha1.NodePropagateRequest
	21, // 15: wpi.v1alpha1.NodeService.NodeTranslateAndMap:input_type -> wpi.v1alpha1.NodeTranslateAndMapRequest
	3,  // 16: wpi.v1alpha1.IdentityService.GetPluginInfo:output_type -> wpi.v1alpha1.GetPluginInfoResponse
	5,  // 17: wpi.v1alpha1.IdentityService.GetPluginCapabilities:output_type -> wpi.v1alpha1.GetPluginCapabilitiesResponse
	7,  // 18: wpi.v1alpha1.ControllerService.CreateWeightBuffer:output_type -> wpi.v1alpha1.CreateWeightBufferResponse
	9,  // 19: wpi.v1alpha1.ControllerService.AuthorizeTransfer:output_type -> wpi.v1alpha1.AuthorizeTransferResponse
	11, // 20: wpi.v1alpha1.ControllerService.QueryTopology:output_type -> wpi.v1alpha1.QueryTopologyResponse
	13, // 21: wpi.v1alpha1.NodeService.NodeRegisterWeight:output_type -> wpi.v1alpha1.NodeRegisterWeightResponse
	15, // 22: wpi.v1alpha1.NodeService.NodeStageWeight:output_type -> wpi.v1alpha1.NodeStageWeightResponse
	17, // 23: wpi.v1alpha1.NodeService.NodeUnstageWeight:output_type -> wpi.v1alpha1.NodeUnstageWeightResponse
	20, // 24: wpi.v1alpha1.NodeService.NodePropagate:output_type -> wpi.v1alpha1.NodePropagateResponse
	22, // 25: wpi.v1alpha1.NodeService.NodeTranslateAndMap:output_type -> wpi.v1alpha1.NodeTranslateAndMapResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_wpi_proto_init() }
func file_wpi_proto_init() {
	if File_wpi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wpi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginCapabilitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginCapabilitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeightBufferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWeightBufferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeTransferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeTransferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTopologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTopologyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRegisterWeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRegisterWeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStageWeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeStageWeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeUnstageWeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeUnstageWeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LayoutDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodePropagateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodePropagateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeTranslateAndMapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeTranslateAndMapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wpi_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginCapabilitiesResponse_PluginCapability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wpi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_wpi_proto_goTypes,
		DependencyIndexes: file_wpi_proto_depIdxs,
		EnumInfos:         file_wpi_proto_enumTypes,
		MessageInfos:      file_wpi_proto_msgTypes,
	}.Build()
	File_wpi_proto = out.File
	file_wpi_proto_rawDesc = nil
	file_wpi_proto_goTypes = nil
	file_wpi_proto_depIdxs = nil
}
