// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: wpi.proto

package wpi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error)
	GetPluginCapabilities(ctx context.Context, in *GetPluginCapabilitiesRequest, opts ...grpc.CallOption) (*GetPluginCapabilitiesResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error) {
	out := new(GetPluginInfoResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.IdentityService/GetPluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetPluginCapabilities(ctx context.Context, in *GetPluginCapabilitiesRequest, opts ...grpc.CallOption) (*GetPluginCapabilitiesResponse, error) {
	out := new(GetPluginCapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.IdentityService/GetPluginCapabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility
type IdentityServiceServer interface {
	GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error)
	GetPluginCapabilities(context.Context, *GetPluginCapabilitiesRequest) (*GetPluginCapabilitiesResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIdentityServiceServer struct {
}

func (UnimplementedIdentityServiceServer) GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedIdentityServiceServer) GetPluginCapabilities(context.Context, *GetPluginCapabilitiesRequest) (*GetPluginCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPluginCapabilities not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.IdentityService/GetPluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetPluginInfo(ctx, req.(*GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetPluginCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetPluginCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.IdentityService/GetPluginCapabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetPluginCapabilities(ctx, req.(*GetPluginCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wpi.v1alpha1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPluginInfo",
			Handler:    _IdentityService_GetPluginInfo_Handler,
		},
		{
			MethodName: "GetPluginCapabilities",
			Handler:    _IdentityService_GetPluginCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wpi.proto",
}

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	CreateWeightBuffer(ctx context.Context, in *CreateWeightBufferRequest, opts ...grpc.CallOption) (*CreateWeightBufferResponse, error)
	AuthorizeTransfer(ctx context.Context, in *AuthorizeTransferRequest, opts ...grpc.CallOption) (*AuthorizeTransferResponse, error)
	QueryTopology(ctx context.Context, in *QueryTopologyRequest, opts ...grpc.CallOption) (*QueryTopologyResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) CreateWeightBuffer(ctx context.Context, in *CreateWeightBufferRequest, opts ...grpc.CallOption) (*CreateWeightBufferResponse, error) {
	out := new(CreateWeightBufferResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.ControllerService/CreateWeightBuffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) AuthorizeTransfer(ctx context.Context, in *AuthorizeTransferRequest, opts ...grpc.CallOption) (*AuthorizeTransferResponse, error) {
	out := new(AuthorizeTransferResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.ControllerService/AuthorizeTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) QueryTopology(ctx context.Context, in *QueryTopologyRequest, opts ...grpc.CallOption) (*QueryTopologyResponse, error) {
	out := new(QueryTopologyResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.ControllerService/QueryTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility
type ControllerServiceServer interface {
	CreateWeightBuffer(context.Context, *CreateWeightBufferRequest) (*CreateWeightBufferResponse, error)
	AuthorizeTransfer(context.Context, *AuthorizeTransferRequest) (*AuthorizeTransferResponse, error)
	QueryTopology(context.Context, *QueryTopologyRequest) (*QueryTopologyResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServiceServer struct {
}

func (UnimplementedControllerServiceServer) CreateWeightBuffer(context.Context, *CreateWeightBufferRequest) (*CreateWeightBufferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWeightBuffer not implemented")
}
func (UnimplementedControllerServiceServer) AuthorizeTransfer(context.Context, *AuthorizeTransferRequest) (*AuthorizeTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeTransfer not implemented")
}
func (UnimplementedControllerServiceServer) QueryTopology(context.Context, *QueryTopologyRequest) (*QueryTopologyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTopology not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_CreateWeightBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWeightBufferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).CreateWeightBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.ControllerService/CreateWeightBuffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).CreateWeightBuffer(ctx, req.(*CreateWeightBufferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_AuthorizeTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).AuthorizeTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.ControllerService/AuthorizeTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).AuthorizeTransfer(ctx, req.(*AuthorizeTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_QueryTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).QueryTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.ControllerService/QueryTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).QueryTopology(ctx, req.(*QueryTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wpi.v1alpha1.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWeightBuffer",
			Handler:    _ControllerService_CreateWeightBuffer_Handler,
		},
		{
			MethodName: "AuthorizeTransfer",
			Handler:    _ControllerService_AuthorizeTransfer_Handler,
		},
		{
			MethodName: "QueryTopology",
			Handler:    _ControllerService_QueryTopology_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wpi.proto",
}

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	NodeRegisterWeight(ctx context.Context, in *NodeRegisterWeightRequest, opts ...grpc.CallOption) (*NodeRegisterWeightResponse, error)
	NodeStageWeight(ctx context.Context, in *NodeStageWeightRequest, opts ...grpc.CallOption) (*NodeStageWeightResponse, error)
	NodeUnstageWeight(ctx context.Context, in *NodeUnstageWeightRequest, opts ...grpc.CallOption) (*NodeUnstageWeightResponse, error)
	NodePropagate(ctx context.Context, in *NodePropagateRequest, opts ...grpc.CallOption) (*NodePropagateResponse, error)
	NodeTranslateAndMap(ctx context.Context, in *NodeTranslateAndMapRequest, opts ...grpc.CallOption) (*NodeTranslateAndMapResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) NodeRegisterWeight(ctx context.Context, in *NodeRegisterWeightRequest, opts ...grpc.CallOption) (*NodeRegisterWeightResponse, error) {
	out := new(NodeRegisterWeightResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.NodeService/NodeRegisterWeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodeStageWeight(ctx context.Context, in *NodeStageWeightRequest, opts ...grpc.CallOption) (*NodeStageWeightResponse, error) {
	out := new(NodeStageWeightResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.NodeService/NodeStageWeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodeUnstageWeight(ctx context.Context, in *NodeUnstageWeightRequest, opts ...grpc.CallOption) (*NodeUnstageWeightResponse, error) {
	out := new(NodeUnstageWeightResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.NodeService/NodeUnstageWeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodePropagate(ctx context.Context, in *NodePropagateRequest, opts ...grpc.CallOption) (*NodePropagateResponse, error) {
	out := new(NodePropagateResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.NodeService/NodePropagate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) NodeTranslateAndMap(ctx context.Context, in *NodeTranslateAndMapRequest, opts ...grpc.CallOption) (*NodeTranslateAndMapResponse, error) {
	out := new(NodeTranslateAndMapResponse)
	err := c.cc.Invoke(ctx, "/wpi.v1alpha1.NodeService/NodeTranslateAndMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	NodeRegisterWeight(context.Context, *NodeRegisterWeightRequest) (*NodeRegisterWeightResponse, error)
	NodeStageWeight(context.Context, *NodeStageWeightRequest) (*NodeStageWeightResponse, error)
	NodeUnstageWeight(context.Context, *NodeUnstageWeightRequest) (*NodeUnstageWeightResponse, error)
	NodePropagate(context.Context, *NodePropagateRequest) (*NodePropagateResponse, error)
	NodeTranslateAndMap(context.Context, *NodeTranslateAndMapRequest) (*NodeTranslateAndMapResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) NodeRegisterWeight(context.Context, *NodeRegisterWeightRequest) (*NodeRegisterWeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeRegisterWeight not implemented")
}
func (UnimplementedNodeServiceServer) NodeStageWeight(context.Context, *NodeStageWeightRequest) (*NodeStageWeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeStageWeight not implemented")
}
func (UnimplementedNodeServiceServer) NodeUnstageWeight(context.Context, *NodeUnstageWeightRequest) (*NodeUnstageWeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeUnstageWeight not implemented")
}
func (UnimplementedNodeServiceServer) NodePropagate(context.Context, *NodePropagateRequest) (*NodePropagateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodePropagate not implemented")
}
func (UnimplementedNodeServiceServer) NodeTranslateAndMap(context.Context, *NodeTranslateAndMapRequest) (*NodeTranslateAndMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeTranslateAndMap not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_NodeRegisterWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeRegisterWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.NodeService/NodeRegisterWeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeRegisterWeight(ctx, req.(*NodeRegisterWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodeStageWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStageWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeStageWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.NodeService/NodeStageWeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeStageWeight(ctx, req.(*NodeStageWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodeUnstageWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeUnstageWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeUnstageWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.NodeService/NodeUnstageWeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeUnstageWeight(ctx, req.(*NodeUnstageWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodePropagate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodePropagateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodePropagate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.NodeService/NodePropagate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodePropagate(ctx, req.(*NodePropagateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_NodeTranslateAndMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeTranslateAndMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).NodeTranslateAndMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wpi.v1alpha1.NodeService/NodeTranslateAndMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).NodeTranslateAndMap(ctx, req.(*NodeTranslateAndMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wpi.v1alpha1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeRegisterWeight",
			Handler:    _NodeService_NodeRegisterWeight_Handler,
		},
		{
			MethodName: "NodeStageWeight",
			Handler:    _NodeService_NodeStageWeight_Handler,
		},
		{
			MethodName: "NodeUnstageWeight",
			Handler:    _NodeService_NodeUnstageWeight_Handler,
		},
		{
			MethodName: "NodePropagate",
			Handler:    _NodeService_NodePropagate_Handler,
		},
		{
			MethodName: "NodeTranslateAndMap",
			Handler:    _NodeService_NodeTranslateAndMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wpi.proto",
}
